"""
    Amazon Ads API - Sponsored Products

    Use the Amazon Ads API for Sponsored Products for campaign, ad group, keyword, negative keyword, and product ad management operations. For more information about Sponsored Products, see the [Sponsored Products Support Center](https://advertising.amazon.com/help?entityId=ENTITY3CWETCZD9HEG2#GWGFKPEWVWG2CLUJ). For onboarding information, see the [account setup](setting-up/account-setup) topic.<br/><br/>   # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import amazon_ads_sponsored_products_client
from amazon_ads_sponsored_products_client.api.bid_recommendations_api import BidRecommendationsApi  # noqa: E501


class TestBidRecommendationsApi(unittest.TestCase):
    """BidRecommendationsApi unit test stubs"""

    def setUp(self):
        self.api = BidRecommendationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_keyword_bid_recommendations(self):
        """Test case for create_keyword_bid_recommendations

        Gets bid recommendations for keywords.  # noqa: E501
        """
        pass

    def test_get_ad_group_bid_recommendations(self):
        """Test case for get_ad_group_bid_recommendations

        Gets a bid recommendation for an ad group.  # noqa: E501
        """
        pass

    def test_get_bid_recommendations(self):
        """Test case for get_bid_recommendations

        Gets a list of bid recommendations for keyword, product, or auto targeting expressions.  # noqa: E501
        """
        pass

    def test_get_keyword_bid_recommendations(self):
        """Test case for get_keyword_bid_recommendations

        Gets a bid recommendation for a keyword.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
