"""
    Amazon Ads API - Sponsored Products

    Use the Amazon Ads API for Sponsored Products for campaign, ad group, keyword, negative keyword, and product ad management operations. For more information about Sponsored Products, see the [Sponsored Products Support Center](https://advertising.amazon.com/help?entityId=ENTITY3CWETCZD9HEG2#GWGFKPEWVWG2CLUJ). For onboarding information, see the [account setup](setting-up/account-setup) topic.<br/><br/>   # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import amazon_ads_sponsored_products_client
from amazon_ads_sponsored_products_client.api.negative_product_targeting_api import NegativeProductTargetingApi  # noqa: E501


class TestNegativeProductTargetingApi(unittest.TestCase):
    """NegativeProductTargetingApi unit test stubs"""

    def setUp(self):
        self.api = NegativeProductTargetingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_archive_negative_targeting_clause(self):
        """Test case for archive_negative_targeting_clause

        Archives a negative targeting clause.  # noqa: E501
        """
        pass

    def test_create_negative_targeting_clauses(self):
        """Test case for create_negative_targeting_clauses

        Creates one ore more negative targeting expressions.  # noqa: E501
        """
        pass

    def test_get_negative_targeting_clause(self):
        """Test case for get_negative_targeting_clause

        Get a negative targeting clause specified by identifier.  # noqa: E501
        """
        pass

    def test_get_negative_targeting_clause_ex(self):
        """Test case for get_negative_targeting_clause_ex

        Get a negative targeting clause specified by identifier.  # noqa: E501
        """
        pass

    def test_list_negative_targeting_clauses(self):
        """Test case for list_negative_targeting_clauses

        Gets a list of negative targeting clauses filtered by specified criteria.  # noqa: E501
        """
        pass

    def test_list_negative_targeting_clauses_ex(self):
        """Test case for list_negative_targeting_clauses_ex

        Gets a list of negative targeting clauses filtered by specified criteria.  # noqa: E501
        """
        pass

    def test_update_negative_targeting_clause(self):
        """Test case for update_negative_targeting_clause

        Updates one or more negative targeting clauses.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
