"""
    Amazon Ads API - Sponsored Products

    Use the Amazon Ads API for Sponsored Products for campaign, ad group, keyword, negative keyword, and product ad management operations. For more information about Sponsored Products, see the [Sponsored Products Support Center](https://advertising.amazon.com/help?entityId=ENTITY3CWETCZD9HEG2#GWGFKPEWVWG2CLUJ). For onboarding information, see the [account setup](setting-up/account-setup) topic.<br/><br/>   # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import amazon_ads_sponsored_products_client
from amazon_ads_sponsored_products_client.api.ad_groups_api import AdGroupsApi  # noqa: E501


class TestAdGroupsApi(unittest.TestCase):
    """AdGroupsApi unit test stubs"""

    def setUp(self):
        self.api = AdGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_archive_ad_group(self):
        """Test case for archive_ad_group

        Archives an ad group.  # noqa: E501
        """
        pass

    def test_create_ad_groups(self):
        """Test case for create_ad_groups

        Creates one or more ad groups.  # noqa: E501
        """
        pass

    def test_get_ad_group(self):
        """Test case for get_ad_group

        Gets an ad group specified by identifier.  # noqa: E501
        """
        pass

    def test_get_ad_group_ex(self):
        """Test case for get_ad_group_ex

        Gets an ad group that has extended data fields.  # noqa: E501
        """
        pass

    def test_get_ad_groups(self):
        """Test case for get_ad_groups

        Gets one or more ad groups.  # noqa: E501
        """
        pass

    def test_get_ad_groups_ex(self):
        """Test case for get_ad_groups_ex

        Gets ad groups that have extended data fields.  # noqa: E501
        """
        pass

    def test_update_ad_groups(self):
        """Test case for update_ad_groups

        Updates one or more ad groups.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
