"""
    Amazon Ads API - Sponsored Products

    Use the Amazon Ads API for Sponsored Products for campaign, ad group, keyword, negative keyword, and product ad management operations. For more information about Sponsored Products, see the [Sponsored Products Support Center](https://advertising.amazon.com/help?entityId=ENTITY3CWETCZD9HEG2#GWGFKPEWVWG2CLUJ). For onboarding information, see the [account setup](setting-up/account-setup) topic.<br/><br/>   # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import amazon_ads_sponsored_products_client
from amazon_ads_sponsored_products_client.api.campaign_negative_keywords_api import CampaignNegativeKeywordsApi  # noqa: E501


class TestCampaignNegativeKeywordsApi(unittest.TestCase):
    """CampaignNegativeKeywordsApi unit test stubs"""

    def setUp(self):
        self.api = CampaignNegativeKeywordsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_archive_campaign_negative_keyword(self):
        """Test case for archive_campaign_negative_keyword

        Archives a campaign negative keyword.  # noqa: E501
        """
        pass

    def test_create_campaign_negative_keywords(self):
        """Test case for create_campaign_negative_keywords

        Creates one or more campaign negative keywords.  # noqa: E501
        """
        pass

    def test_get_campaign_negative_keyword(self):
        """Test case for get_campaign_negative_keyword

        Gets a campaign negative keyword specified by identifier.  # noqa: E501
        """
        pass

    def test_get_campaign_negative_keyword_ex(self):
        """Test case for get_campaign_negative_keyword_ex

        Gets a campaign negative keyword that has extended data fields.  # noqa: E501
        """
        pass

    def test_list_campaign_negative_keywords(self):
        """Test case for list_campaign_negative_keywords

        Gets a list of campaign negative keywords.  # noqa: E501
        """
        pass

    def test_list_campaign_negative_keywords_ex(self):
        """Test case for list_campaign_negative_keywords_ex

        Gets a list of campaign negative keywords that have extended data fields.  # noqa: E501
        """
        pass

    def test_update_campaign_negative_keywords(self):
        """Test case for update_campaign_negative_keywords

        Updates one or more campaign negative keywords.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
