"""
    Amazon Ads API - Sponsored Products

    Use the Amazon Ads API for Sponsored Products for campaign, ad group, keyword, negative keyword, and product ad management operations. For more information about Sponsored Products, see the [Sponsored Products Support Center](https://advertising.amazon.com/help?entityId=ENTITY3CWETCZD9HEG2#GWGFKPEWVWG2CLUJ). For onboarding information, see the [account setup](setting-up/account-setup) topic.<br/><br/>   # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import amazon_ads_sponsored_products_client
from amazon_ads_sponsored_products_client.model.get_asin_suggested_keywords_response_suggested_keywords import GetAsinSuggestedKeywordsResponseSuggestedKeywords
globals()['GetAsinSuggestedKeywordsResponseSuggestedKeywords'] = GetAsinSuggestedKeywordsResponseSuggestedKeywords
from amazon_ads_sponsored_products_client.model.get_asin_suggested_keywords_response import GetAsinSuggestedKeywordsResponse


class TestGetAsinSuggestedKeywordsResponse(unittest.TestCase):
    """GetAsinSuggestedKeywordsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAsinSuggestedKeywordsResponse(self):
        """Test GetAsinSuggestedKeywordsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAsinSuggestedKeywordsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
