"""
    Amazon Ads API - Sponsored Products

    Use the Amazon Ads API for Sponsored Products for campaign, ad group, keyword, negative keyword, and product ad management operations. For more information about Sponsored Products, see the [Sponsored Products Support Center](https://advertising.amazon.com/help?entityId=ENTITY3CWETCZD9HEG2#GWGFKPEWVWG2CLUJ). For onboarding information, see the [account setup](setting-up/account-setup) topic.<br/><br/>   # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import amazon_ads_sponsored_products_client
from amazon_ads_sponsored_products_client.api.product_ads_api import ProductAdsApi  # noqa: E501


class TestProductAdsApi(unittest.TestCase):
    """ProductAdsApi unit test stubs"""

    def setUp(self):
        self.api = ProductAdsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_archive_product_ad(self):
        """Test case for archive_product_ad

        Archives a product ad.  # noqa: E501
        """
        pass

    def test_create_product_ads(self):
        """Test case for create_product_ads

        Creates one or more product ads.  # noqa: E501
        """
        pass

    def test_get_product_ad(self):
        """Test case for get_product_ad

        Gets a product ad specified by identifier.  # noqa: E501
        """
        pass

    def test_get_product_ad_ex(self):
        """Test case for get_product_ad_ex

        Gets extended data for a product ad specified by identifier.  # noqa: E501
        """
        pass

    def test_list_product_ads(self):
        """Test case for list_product_ads

        Gets a list of product ads filtered by specified criteria.  # noqa: E501
        """
        pass

    def test_list_product_ads_ex(self):
        """Test case for list_product_ads_ex

        Gets extended data for a list of product ads filtered by specified criteria.  # noqa: E501
        """
        pass

    def test_update_product_ads(self):
        """Test case for update_product_ads

        Updates one or more product ads specified by identifier.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
