"""
    Amazon Ads API - Sponsored Products

    Use the Amazon Ads API for Sponsored Products for campaign, ad group, keyword, negative keyword, and product ad management operations. For more information about Sponsored Products, see the [Sponsored Products Support Center](https://advertising.amazon.com/help?entityId=ENTITY3CWETCZD9HEG2#GWGFKPEWVWG2CLUJ). For onboarding information, see the [account setup](setting-up/account-setup) topic.<br/><br/>   # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import amazon_ads_sponsored_products_client
from amazon_ads_sponsored_products_client.api.reports_api import ReportsApi  # noqa: E501


class TestReportsApi(unittest.TestCase):
    """ReportsApi unit test stubs"""

    def setUp(self):
        self.api = ReportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_report(self):
        """Test case for download_report

        Downloads a previously requested report identified by report ID.  # noqa: E501
        """
        pass

    def test_get_report(self):
        """Test case for get_report

        Gets a previously requested report specified by identifier.  # noqa: E501
        """
        pass

    def test_request_report(self):
        """Test case for request_report

        Requests a Sponsored Products report.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
